# Generated by Django 6.0.4 on 2026-05-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_realtors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
