# Generated by Django 6.0.4 on 2026-05-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='property_dtd',
            new_name='property_detail',
        ),
    ]
