# Generated by Django 6.0.4 on 2026-05-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_property_dtd_bookingmodel_property_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='advance',
            new_name='advance_amount',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='rent',
            new_name='rentamount',
        ),
    ]
