# Generated by Django 6.0.4 on 2026-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_balcony_bathroom_kitchen_livingarea_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livingarea',
            old_name='livin_pics',
            new_name='living_pics',
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen_pics',
            field=models.ImageField(blank=True, null=True, upload_to='kicthen/'),
        ),
    ]
