# Generated by Django 6.0.4 on 2026-05-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_enquiry'),
        ('properties', '0005_rename_livin_pics_livingarea_living_pics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('EMI', 'Book With EMI'), ('ADVANCE', 'Book Advance')], max_length=20)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('emi_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.allproperties')),
                ('realall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.realtors')),
            ],
        ),
    ]
