# Generated by Django 6.0.4 on 2026-05-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertybooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybooking',
            name='realall',
        ),
    ]
