# Generated by Django 6.0.4 on 2026-05-21 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_enquiry'),
        ('properties', '0007_remove_propertybooking_realall'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybooking',
            name='realtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formapp.realtors'),
            preserve_default=False,
        ),
    ]
