# Generated by Django 6.0.4 on 2026-05-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertybooking_realtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybooking',
            name='realtor',
        ),
    ]
